{% raw %}
name: Lint

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  lint:
    strategy:
      matrix:
        linter:
          - name: Flake8
            run: flake8 --config=setup.cfg
          - name: Black
            run: black --check .
          - name: PyUpgrade
            run: pyupgrade --py3-plus `find . -name "*.py"`
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install Dependencies
      run: |
        python -m pip install -U pip
        pip install -r requirements.txt
    - name: ${{ matrix.linter.name }}
      run: ${{ matrix.linter.run }}
{% endraw %}
